[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.build]
cmds = ["cd 'solana-contract/solana_smart_contract' && npm install"]

[start]
cmd = "cd 'solana-contract/solana_smart_contract' && node moonpay-webhook-handler.js"